### ISSUE TITLE
[redmine plugin] 意図しないメッセージで反応してしまう

### ISSUE THREAD

**Issue by altnight** [beproud/beproudbot#105]
### 目的

- redmine のチケットを表す `t<xxx>` で反応させたいけど、 `t<xxx>/hogemoge` など意図しないメッセージでは反応させたくない

### 入出力

- redmine plugin で API key を登録したユーザーの場合、反応する

### 関連機能、影響範囲

- redmine plugin

### セキュリティ

- なし

### デモ方法

-

**Comment by altnight** [comment]
案

- ユーザー種別
  - 通常ユーザー: 反応させる
  - bot,appユーザー: 反応させない
- redmine plugin の API Key
  - 有効: 反応させる
  - 無効: 反応させない
- メッセージ
  - `t12`: 反応させる
  - `t12345`: 反応させる
  - `feature/t12345`: 反応させたくない
  - `project51` 反応させたくない

**Comment by shimizukawa** [comment]
URLにも反応してほしい気持ち

こういうの

```
https://project.beproud.jp/redmine/issues/58973
https://project.beproud.jp/redmine/issues/58973#note-3
```

**Comment by shimizukawa** [comment]
チケット番号として反応してほしくない書き方

````

`t12345` のようなリテラルの中身や

```
t12345
```
のようなフェンスドリテラルの中身。
````

**Comment by jamesvandyne** [comment]
#110 / #111 をマージしたので、終了します。
