### ISSUE TITLE
スレッドへの応答はスレッド内にする

### ISSUE THREAD

**Issue by crohas** [beproud/beproudbot#107]
### 目的
現状 `++` など特定スレッド内で行われたbotに対するコマンド出力がスレッド外に行われるので、特定スレッドに返すようにしてほしい

### 入出力
入力: スレッドID的なものを受け取る(すでに受け取っているかもしれないけど)
出力: スレッドIDがあればそれに対して返却する(API的にできるなら)

### 関連機能、影響範囲
- スレッド内の投稿全て

### セキュリティ
- 今までと同じで良さそう

### デモ方法
- スレッド内で `++` してみてスレッドに対してbotが応答するか

**Comment by takanory** [comment]
* PyCon JP Botの実装例です
* https://github.com/pyconjp/pyconjpbot/pull/16

**Comment by crohas** [comment]
https://beproud.slack.com/archives/G0291Q891/p1521439744000067?thread_ts=1521437099.000076&cid=G0291Q891 で返ってくること確認したのでクローズ

kashew_nuts++
