### ISSUE TITLE
ファイルアップロード時のタイトル名に++が含まれるとharoが応答するので修正

### ISSUE THREAD

**Issue by wanshot** [beproud/beproudbot#113]
### 目的

- ファイルアップロード時のタイトル名に++が含まれるとharoが応答するので修正する

### 現象

![2017-12-28 14 07 17](https://user-images.githubusercontent.com/13720034/34400854-e6eee578-ebd8-11e7-9fa3-e82c4b947235.jpg)

### 関連機能、影響範囲

- thxコマンド

### セキュリティ

- 特になし

### デモ方法

- Slackの画像ポスト時のタイトル名にthxコマンドを入力する

**Comment by jamesvandyne** [comment]
#129 で対応したので、終了します。
