### ISSUE TITLE
語録登録したURLを呼び出した時にURLの内容が展開されて欲しい

### ISSUE THREAD

**Issue by wanshot** [beproud/beproudbot#116]
### 目的

- 語録登録したURLを呼び出した時にURLの内容が展開されて欲しい

### 関連機能、影響範囲

- createコマンド

- Slackのサーバー側でURLを判別して `<>` をつけている
   - https://api.slack.com/docs/message-formatting
- slackbotはRealTimeMessageで接続している為、haro側で対策をする必要がある

### セキュリティ

- 特に無し

### デモ方法

- $create add test
- $test ttp://nekoneko
- $test

**Comment by pjxiao** [comment]
# お困り事例

```
takanory [11:06]
$zoom https://zoom.us/j/********** (hostkey: `****`)

haro APP [11:06]
コマンド `$zoom` に「<https://zoom.us/j/**********> (hostkey: `****`)」を追加しました

takanory [11:06]
$zoom

haro APP [11:06]
<https://zoom.us/j/**********> (hostkey: `****`)

takanory [11:06]
ぐぬぬ
```

**Comment by wanshot** [comment]
https://github.com/beproud/beproudbot/pull/162
