### ISSUE TITLE
Redmineコマンドのキーを取得する方法を追記する

### ISSUE THREAD

**Issue by kashewnuts** [beproud/beproudbot#120]
### 目的

- 現状RedmineのAPIキーや識別子をどこから取得するのかわからない
- APIキーや識別子を設定する方法を明記することで、Redmineコマンドの導入を楽にする

### 入出力

- READMEにAPIキーを取得方法を追記する
- READMEに識別子の取得方法を追記する

### 関連機能、影響範囲

- なし

**Comment by wanshot** [comment]
https://github.com/beproud/beproudbot/pull/121
