### ISSUE TITLE
create plugin の実装

### ISSUE THREAD

**Issue by takanory** [beproud/beproudbot#13]
### 目的

- 用語(語録)を追加削除できるコマンド群を実装する

### スキーマ

```
(beproudbot@project-db) [beproudbot]> show columns from command;
+----------+--------------+------+-----+---------+----------------+
| Field    | Type         | Null | Key | Default | Extra          |
+----------+--------------+------+-----+---------+----------------+
| id       | int(11)      | NO   | PRI | NULL    | auto_increment |
| command  | varchar(20)  | NO   |     | NULL    |                |
| register | varchar(100) | NO   |     | NULL    |                |
+----------+--------------+------+-----+---------+----------------+
3 rows in set (0.01 sec)
```

```
(beproudbot@project-db) [beproudbot]> show columns from command_words;
+------------+---------------+------+-----+---------+----------------+
| Field      | Type          | Null | Key | Default | Extra          |
+------------+---------------+------+-----+---------+----------------+
| id         | int(11)       | NO   | PRI | NULL    | auto_increment |
| command_id | int(11)       | NO   | MUL | NULL    |                |
| word       | varchar(1024) | NO   |     | NULL    |                |
| register   | varchar(100)  | NO   |     | NULL    |                |
+------------+---------------+------+-----+---------+----------------+
4 rows in set (0.00 sec)
```

### 入出力

`$create add hoge`: hogeコマンドを追加する
`$create del hoge`: hogeコマンドを削除する
`$create list hoge`: createコマンドで登録したコマンド一覧を表示する
`$hoge huga`: hugaを語録として追加する
`$hoge del huga`: hugaを語録から削除する
`$hoge rm huga`: hugaを語録から削除する
`$hoge pop`: 最後に追加した語録を削除する
`$hoge list`: 語録の一覧を返す
`$hoge search <keyword>`: 語録の一覧からキーワードにマッチするものを返す
`$create help`: createコマンドの使い方を返す

### 関連機能、影響範囲

- 既存の語録をそのまま移行する必要がある

### セキュリティ

- 現在の _pop はユーザーごとに見ているけど、不要にするならセキュリティとかは関係なくなりそう

### デモ方法

(あとでかく)

**Comment by wanshot** [comment]
このコマンドの実装はslackbotの仕様上、各コマンドの関数定義はslackbotのプロセスを起動した時にされるから提供されているインターフェイスでなんとかやるのは無理そう。

選択肢
A. slackbotにパッチを当てる
   1. slackbot.manager.PluginManagerのクラス変数のcommandsを書き換える
   2. 現在のコマンドは `huga 用語` となっているコマンドを `hoge huga 用語` という風にして、関数ないで判定させる

B. フレークワークを変える
   - 要検討

C. その他

**Comment by takanory** [comment]
え、どういうこと??こんな感じで実装したよ。
https://github.com/pyconjp/pyconjpbot/blob/master/pyconjpbot/plugins/term.py

**Comment by wanshot** [comment]
https://github.com/beproud/beproudbot/pull/47
