### ISSUE TITLE
ぷらぷらの誤爆防止

### ISSUE THREAD

**Issue by kashewnuts** [beproud/beproudbot#130]
### 目的

- diffを投稿した際、 `+はSlackのユーザーとして存在しません` などと表示されるのを防止する

### 入出力

- 入力

```
diff --git a/apps/apps/settings.py b/apps/apps/settings.py
index 3065de8..71727b6 100644
--- a/apps/apps/settings.py
+++ b/apps/apps/settings.py
@@ -149,6 +149,9 @@
...
```

- 出力(期待する結果)

ぷらぷらが反応しない。

### 関連機能、影響範囲

- リグレッションの確認が必要となる箇所: `kudo.py` (, `thx.py` もかな)

### セキュリティ

- 特になし

**Comment by kashewnuts** [comment]
ぷらぷらに限らず、コードブロック内は無視するようにできたらいいなという妄想はある。

**Comment by takanory** [comment]
* +1
* コードブロック認識かー、正規表現でできなくはないかなぁ...

**Comment by kashewnuts** [comment]
https://beproud.slack.com/archives/C1K418VJT/p1535157925000100 のようにRSSで取得した本文にも反応することがあるが、エッジケースなため無視してよさそう。当初の目的は果たされているのでcloseします。
