### ISSUE TITLE
redmineの期限切れタスクを定期通知

### ISSUE THREAD

**Issue by takanory** [beproud/beproudbot#137]
### 目的

- チャンネルと関連付けられたredmineのタスク一覧を取得し、もうすぐ期日となる、または期日を過ぎたチケットの一覧を通知する
- 一覧が担当者のメンション付きでチャンネルに通知されることにより「チケットが放置される」ことを防ぐ
- 通知されるために各チケットに期日を設定する癖をつける

### やること
* [x] DBに格納されているredmineとチャンネル一覧を取得
  * [x] 実装
* [x] redmineのタスク一覧を取得
  * [x] 実装
* [x]  もうすぐ期日となる、または期日を過ぎたチケットの一覧を分ける
  * [x] 実装
* [x] 整理したチケット情報をSlackに通知
  * [x] 実装
* [x] 動作確認
  * [x] ローカル
* [x] JSON導入
  * [x] 実装
* [x] 動作確認(JSON導入後)
  * [x] ローカル
* [x] マージ
* [x] リリース
* [x] 動作確認(リリース後)
  * [x] 本番
* [ ] 定期的にredmine通知処理を実行する(定期通知は毎週月曜日の午前9時に行う)
  * [x] 定期通知処理の仕方をチェンネル内で確認
  * [x] 実装方法の選定
  * [ ] 実装(リリース後にsystemdのTimerを設定)

### スケジュール

1,7月12日
- 動作確認

2,7月13日
- JSON導入

3,7月14日
- 再度動作確認

4,7月17日
- 本番リリース

### 実装方法
**src/redmine_notification.pyに格納**

- systemdでtimerを作成、新たに.pyファイルを作成し、実行するPythonプログラムを用意する。
timerで毎週月曜日の朝9時にPythonプログラムを実行するよう設定。

https://qiita.com/aosho235/items/7656d5568af8f48b2dc1#%E3%82%BF%E3%82%A4%E3%83%9E%E3%83%BC%E3%82%92%E5%81%9C%E6%AD%A2%E3%81%99%E3%82%8B```

- 設定したタイマーに従い(毎週月曜日、朝9時)、Pythonスクリプトを実行する。

- RedmineのAPIからチケット情報を取得
 
-  各プロジェクトのproj_roomを獲得する。

- 期限が切れたチケットと期限が切れそうなチケットに分ける

- 各チャンネルにチケット情報を送信する
   -send_slack_message を使用し、チケット情報を送信する。

### 入出力

- 入力はなく、できれば定期的に(毎週月曜朝とか)に一覧が通知されてほしい
  - どういう仕組みで定期通知するかはチャンネルにいる人と相談するとよさそう
  - cron? bot自体に定期実行機能つける?
- 出力: PyCon JPだとこんな感じでcronで通知している

<img width="797" alt="pyconjp-jirabot" src="https://user-images.githubusercontent.com/988241/41522502-2f38a8e0-7311-11e8-8b5f-0109e5dbc866.png">

### 関連機能、影響範囲

- この機能が使うデータを生成する機能
  - redmineコマンドで作成されたチャンネルとredmineの関連付け情報が必要

### セキュリティ

- redmine上のユーザー名とSlackとのユーザー名の関連付けが必要

**Comment by daikikuchi** [comment]
やること記入。随時、追加していく。

**Comment by daikikuchi** [comment]
# Slack上の重要なことを記録していく


# 6月22日(金)

# 定期的にredmine通知処理する方法まとめ

- 定期通知は、毎週月曜日9時にしたい

- slackチャンネルとredmineプロジェクトの関連情報は、DB(社内DBサーバーにある)

- メンテナンスを開発者がやれればいいのなら、ハードコード(直接pythonコードやsystemd timer など)する想定でもいいし、botのコマンドで操作したいならDBにいれる

## 定期通知の方法案まとめ

### 1,_threadは使用しない　理由: 考慮する事が多い＆複雑になる、スケジュール管理に向かない

### 2, Google Scriptはバージョン管理が大変、コード書くのも手間になるから使わない。
- haroとredmineは社内ネットワーク(社内VM)に配置しているから、GAS(インターネット) から社内ネットワー 
   クへのアクセス許可をしたくない。

### 3,期限切れのチケットを教えてくれるコマンドをharoに実装して、systemd timerで定時にharoにポストするスクリプトを書く

メリット:
- 実装のイメージがつきやすい。

デメリット:
- systemd timerつかったこと無いから、調べるのに時間がかかる。

- インフラ周り(systemd timerどこに設定するのか、DBの共有とか)も関連してくるので、作業量多くなる。=>haroからDBアクセスするので考慮不要っす(wanさん発言)

### 4,bpredmine で haro に向けてリクエスト(コマンドを作成するか、webhook等のURLをharoのVMに用意する)

* bpredmine VM 内で、redmine のチケットの期限切れチケットを取得。チャンネル情報等も取得。
* bpredmine VM 内で、取得結果を整形し、 haro に発言させる
* A案): bpredmine 内から slack につないでharoにDMし、haroのコマンドで発言させる(haroにコマンド実装が必要)
* B案): haro VM 内でサーバーを起動しておき、そのURLにアクセスがきたら haro のトークンを使って発言させる(たぶんできるけど未確認)

メリット: 
- 今回は特にメリットにならないが、定期実行させるホスト(VM)はbot(haro)じゃなくてもいい、haro VM 内でサーバーが立ち上がっていてハンドリングする仕組みがあると他に使い回せる(かもしれない)

デメリット:
- 出来るかどうか分からない、めんどくさそう。

### 5,haroの環境を利用して新たにスケジューラーアプリ立てる(systemd timerで定期実行。DBだけ同じものを使う)

メリット:
- slackbotのやり方にのらなくていい(slackbotはhttps://api.slack.com/rtmを利用する事を想定して作られるているので)

デメリット:
- 一から設計実装する手間がかかる
- 管理するアプリが増える

**Comment by daikikuchi** [comment]
# 6月22日(金)

# 定期的にredmine通知処理する実装方法

### 下記の方法が良ければ明日から実装に入っていく

### - systemdでtimerを作成、新たに.pyファイルを作成し、実行するPythonプログラムを用意する。

timerで毎週月曜日の朝9時にPythonプログラムを実行するよう設定。

https://qiita.com/aosho235/items/7656d5568af8f48b2dc1#%E3%82%BF%E3%82%A4%E3%83%9E%E3%83%BC%E3%82%92%E5%81%9C%E6%AD%A2%E3%81%99%E3%82%8B```

### - 設定したタイマーに従い(毎週月曜日、朝9時)、Pythonプログラムを実行する。
1, RedmineのAPIからチケット情報とチケット作成者を取得

参照:
RedmineAPIを操作するライブラリを利用したRedmineコマンドを参考にしてください。
これが仕様っぽい感じ
https://github.com/beproud/beproudbot/blob/master/docs/redmine.rst
これがコード
https://github.com/beproud/beproudbot/blob/master/src/haro/plugins/redmine.py

2,期限が切れたチケットと期限が切れそうなチケットに分ける

＊for loopを使用し振り分ける

3,各チャンネルにチケット情報を送信する
slacker libraryのmessage.sendを使用し、チケット情報を送信する。
参照: https://github.com/lins05/slackbot/blob/develop/slackbot/slackclient.py#L139

### 実装手順:
- Pythonプログラム作成。
・RedmineのAPIからチケット情報とチケット作成者を取得するFunctionを作成
   6月26日(火)
・期限が切れたチケットと期限が切れそうなチケットに分けるFunctionを作成
　6月26日(火)~6月27日(水)
・slacker libraryのmessage.sendを使用し、チケット情報を送信するFunction作成
　6月27日(火)~6月28日(水)

**Comment by takanory** [comment]
* 前提
  * slackclient は Slack API を呼び出すシンプルなプログラム https://github.com/slackapi/python-slackclient
  * api_callの実態はrequestsを使ってSlack APIに対してHTTP POSTしているだけ https://github.com/slackapi/python-slackclient/blob/36cecfa5437a5a7947686f34d9c10b094cf9ce78/slackclient/slackrequest.py#L98
  * メッセージを送信する chat.postMessageの仕様はここ https://api.slack.com/methods/chat.postMessage#channels
* やりたいこと
  * 期限切れチケットを通知するときに、チケット番号にURLのリンクとかを入れたい
  * アイコンとかbot名も変えたい(haroのままじゃない方がいいと思う)
* どう実装するか
  * chat.postMessageをそのまま投げているはずなので、ここにあるパラメーターがそのまま渡せるはず https://api.slack.com/methods/chat.postMessage#channels
  * attachements引数を指定すればよさそう
    * テキストにURLを書いたりといったフォーマット方法は https://api.slack.com/docs/message-formatting
    * attachments の書き方 https://api.slack.com/docs/message-attachments
  * user_name, icon_emoji も指定するとよさそう
* 進め方
  * まずは固定のメッセージを任意のチャンネルに送信する小さなプログラムを書く
  * メッセージにフォーマットつけたり、attachmentsをつけたり、icon_emojiとかを指定して、どう書くとどういう風にSlackにポストされるかを確認する
  * どのように書けば、どうポストされるかを理解したら、redmineの通知に反映させる

**Comment by wanshot** [comment]
Released　#140
