### ISSUE TITLE
Redmineの期限切れタスク: 定期通知の残件やバグのまとめ

### ISSUE THREAD

**Issue by daikikuchi** [beproud/beproudbot#146]
### 目的

- Redmineの期限切れタスクを定期通知の残券やバグのまとめて、wanさんに引き継ぐため

### 残り作業

- systemdのTimerを導入
  - 定期通知は毎週月曜日の午前9時に行う予定
- 通知のUIを変更
  - どのようにUIを変更するのか話し合いが続いてる。
参照メッセージ:https://beproud.slack.com/archives/G0291Q891/p1531888707000099
- TODOを修正
  - Github参照: https://github.com/beproud/beproudbot/blob/master/src/redmine_notification.py#L130

### バグ
- Production環境で`redmine_notification`を実行できない
  - `from haro.plugins.redmine_models import ProjectChannel`を修正する
- 通知の名前をチケット`作成者`から`担当者に変更`する
  - 参照: https://github.com/beproud/beproudbot/compare/t145-notify-to-assined-person

### 関連チケット
- #137
- #145

**Comment by takanory** [comment]
* shimizukawaは8時通知がいいらしい

**Comment by wanshot** [comment]
https://github.com/beproud/beproudbot/pull/150
