### ISSUE TITLE
redmine_notifiaction: チケットの詳細も本文に入れてほしい

### ISSUE THREAD

**Issue by takanory** [beproud/beproudbot#153]
### 目的

- 現在の通知では、チケットの一覧は attachements に入っている
- SlackのActivityで見るとタイトル「もうすぐ期限が切れそうなチケットは2件です」しか出ないので、詳細を見に行かないと行けない
- メンションされていたら全部でてくれたほうが便利そう?

<img width="493" alt="screen shot 2018-07-30 at 9 43 23" src="https://user-images.githubusercontent.com/988241/43372621-ae616778-93dd-11e8-80e0-8ed34f3f160c.png">

### 入出力

- 入力はいままでどおり
- 出力は text に全てのチケット情報がメンションも含めて入っている

### 関連機能、影響範囲

- とくになし

### セキュリティ

- とくになし

**Comment by NaoY-2501** [comment]
@takanory チケットがメンションに入るようになっていますが、この状態とは少し違うという感じですか？
![2020-11-04_12_37_14](https://user-images.githubusercontent.com/22150881/98066644-f5a59b00-1e9a-11eb-8fff-1bb242976135.png)

**Comment by takanory** [comment]
すでに対応済でOKです!!!
