### ISSUE TITLE
Redmine URL自動展開の削減

### ISSUE THREAD

**Issue by shimizukawa** [beproud/beproudbot#154]
### 目的

- Redmine URL展開がうざいので必要最小限にしてチャットが流れないようにしたい
- URL展開をSlack管理者権限で削除する人が散見される（そのうち誤操作で人の発言削除しそうでこわい）ので、そうしなくてよい世界にしたい

### 入出力

入力

- RedmineのURL
- 例: `https://project.beproud.jp/redmine/issues/63642#note-3`

出力

- [x] MUST: チケットタイトル（いままでどおり）
- [x] MUST: Description等の付随情報（折りたたんで欲しい、無理なら表示しなくてよい、スレッドに投稿でも良いかもしれない）
  -> スレッドになった
- [x] チケットタイトルの行に担当者、ステータス、優先度、を含める
- [ ] SHOULD: 8時間以内におなじURLをPOSTされたら、POSTした人にだけ見えるメッセージで「おなじURLの連続POSTだから再展開しないよ」と表示
- [x] HOPE: URLにコメントのハッシュ #note-3 が付いてたら、チケット本文ではなくコメントの方を表示してほしい（これは連続POSTとみなさない）

### 関連機能、影響範囲

- たぶんなし

### セキュリティ

- なし

### デモ方法

- https://project.beproud.jp/redmine/issues/63642#note-7

以下、ログ
```
shimizukawa [16:09]
RedmineのURLを貼るとチケットが展開されるじゃない？
https://project.beproud.jp/redmine/issues/63642

haro APP [16:10]
wan
haro環境にRedmine Nofitication用のsystemd timerを設定する
やる事
---------------

- haro環境に `redmine_notification.py` を実行する systemd timerの設定を行う

このチケットの対象としないこと
----------------------------------------

* systemd timerの設定をharoの構成管理入れる作業
* Redmine Notificationに関連するsystemd timerの設定などをドキュメントとして残す作業(別途haroのissue管理で行う)
担当者
wan
ステータス
終了
優先
通常

shimizukawa [16:10]
で、この展開されたやつを削除する、っていう運用をしてる人達がいるのだけど、じつはこれ役立ってないということなのだろうか

xiao [16:11]
個人的な感想を言うと、 description まで表示されると長すぎ感じがする
タイトル（とあとは担当者とステータスくらい？）でれば十分なんではないかなという
そんな感じです

shimizukawa [16:12]
あと、botのメッセージなので削除できる人は管理者権限を発揮してるのに気づいてるだろうか、っていう別の問題もある

altnight [16:12]
GitHubのissueやPRを貼るごとに全部展開されるのが長くて消すのはわりとする

shimizukawa [16:13]
削除する運用を自然にやってると、まちがえて人間の投稿もさくっと削除しそうでこわいんだよなー

tsutomu [16:13]
URLの展開、よく消しますね。必要性感じないときに。
全部、消すわけではないけど

shimizukawa [16:14]
URLの展開削除は自分の権限でできるので、まあお好きに (edited)
botの発言削除は、そのうち誤操作で他人の発言削除する流れなので、よくない
であればbotのチケット内容展開をみなおしたほうがよさそう
と、思うのだけど、どうだろう
description折りたためるといいよね。無理ならタイトルだけでいいよね
たぶん

xiao [16:16]
きっと

shimizukawa [16:17]
あとは、
`https://project.beproud.jp/redmine/issues/63642#note-7` ってなってたら、descriptionじゃなくnoteの内容表示してほしい（便乗

haro APP [16:17]
wan
haro環境にRedmine Nofitication用のsystemd timerを設定する
やる事
---------------

- haro環境に `redmine_notification.py` を実行する systemd timerの設定を行う

このチケットの対象としないこと
----------------------------------------

* systemd timerの設定をharoの構成管理入れる作業
* Redmine Notificationに関連するsystemd timerの設定などをドキュメントとして残す作業(別途haroのissue管理で行う)
担当者
wan
ステータス
終了
優先
通常

shimizukawa [16:18]
あと同じチケットURLの自動展開は8時間以内に1回までにしてほしい（これは必要っぽい

xiao [16:18]
:chira:  https://github.com/beproud/beproudbot/issues/new
```

**Comment by pjxiao** [comment]
Description は、折りたたむことができない。スレッドに投げるがよさそう。

-  5 行を超えると自動で折りたたまれるとドキュメントに記載されている [^1]
- 折りたたみを手動で設定する方法は今の所なさそう [^2]
- 5 行を越えても折りたたまれないこともあるが、原因不明 [^3]

[^1]: https://api.slack.com/docs/message-attachments
[^2]: https://twitter.com/slackhq/status/458055719913140226?lang=en
[^3]: https://beproud.slack.com/archives/C02TXV8NY/p1533887926000248

**Comment by altnight** [comment]
いくつかパターンを試してみた。スレッドに投げるパターンはまだ試せてない。説明欄の表示が長いという話は、直接表示をいじってみて試すのがいいんじゃないかなと思う

## 通常
説明欄が長いとちょっと流れすぎるかもという話
![g154_normal](https://user-images.githubusercontent.com/314365/44068925-7ace672c-9fb7-11e8-961f-bf7985ac9a1a.png)

## 説明を100文字で切る
改行があるのであんまりコンパクトじゃないかも

![g154_desc_100](https://user-images.githubusercontent.com/314365/44068923-7aa88a2a-9fb7-11e8-99cc-461aa618f323.png)

## タイトル、フィールドのみ
多少コンパクト。このくらいでもいいかもしれない
![g154_title_and_fields](https://user-images.githubusercontent.com/314365/44068921-7a813a6a-9fb7-11e8-8894-69447631b3bc.png)

## タイトルのみ
だいぶコンパクト。このくらいでもいいかもしれない
![g154_title_only](https://user-images.githubusercontent.com/314365/44068920-7a56e8f0-9fb7-11e8-992a-7237044e25e7.png)

**Comment by altnight** [comment]
## スレッドに本文を乗せる
よさそう
![g154_thread](https://user-images.githubusercontent.com/314365/44069394-7c3e84b4-9fb9-11e8-86ca-a006ebb7cdcc.png)

コードはこんな感じで、スレッドIDを指定するだけ `sc.chat.post_message(channel_id, ticket.description, as_user=True, thread_ts=m.body['ts'])`

**Comment by shimizukawa** [comment]
スレッドいいね

ちなみに、RedmineからSlackへの通知時にうまいボリュームにできないかなーとpluginをいじったときの差分がこれ
https://github.com/shimizukawa/redmine-slack/commit/09f159a9c056919a11b242cc310f52f1c4b058a5

**Comment by altnight** [comment]
チケットステータスのfield等もスレッドに移動するかもしれない。しないかもしれない。

**Comment by pjxiao** [comment]
スッドレ +1

**Comment by yyyk-bp** [comment]
スレッド+1

チャンネルに直で出す場合多くても3行くらいにまとまっていてほしいが、いい感じにサマリする手段がなさそうなのでスレッドに全部出しちゃう方が手っ取り早い

**Comment by altnight** [comment]
fields にいれている情報はタイトルにいれて1行でまとめるのもよいかもしれない

例: `[altnight][新規][通常]Test Issue`

**Comment by altnight** [comment]
## タイトルに各種情報をいれて1行表示

こうなる
<img width="544" alt="g154-ttitleinfo" src="https://user-images.githubusercontent.com/314365/44072119-f82f9a64-9fc7-11e8-952e-ad64e49c3f79.png">

**Comment by altnight** [comment]
## タイトルをテキスト表示
少し表示がさびしいかも?リンクになっている方が気持ちわかりやすい
<img width="907" alt="g154-title-text" src="https://user-images.githubusercontent.com/314365/44125796-81b84c16-a06f-11e8-80b4-3a87014b6c41.png">

## タイトルを channel に戻す
`sc.chat.post_message(channel_id, p, as_user=True, thread_ts=message.thread_ts, reply_broadcast=True)` というように `reply_broadcast` をつけるとスレッドの発言をチャンネルにもどせる(slacker 0.9.65 で対応されてるけど、pypiではなくGitHubからダウンロードする必要がある)。
表示としては気持ちいまいち
<img width="922" alt="g154-title-broadcast" src="https://user-images.githubusercontent.com/314365/44125795-819579b6-a06f-11e8-8abe-ac706eb79b16.png">

**Comment by altnight** [comment]
## 通常発言+リンク
`text=<redmineurl/issues/12344|#12345: [担当者なし][通常][新規] Test Issue>` というようなシンタックスで書けばリンクになる。
わりとよさそう

<img width="907" alt="g154-text-link" src="https://user-images.githubusercontent.com/314365/44126153-7798a06c-a071-11e8-8f2f-d098becc6c90.png">

**Comment by shimizukawa** [comment]
良い感じ！！

現状

- [x] MUST: チケットタイトル（いままでどおり）
- [x] MUST: Description等の付随情報（折りたたんで欲しい、無理なら表示しなくてよい、スレッドに投稿でも良いかもしれない）
  -> スレッドになった
- [x] チケットタイトルの行に担当者、ステータス、優先度、を含める(NEW!)
- [ ] SHOULD: 8時間以内におなじURLをPOSTされたら、POSTした人にだけ見えるメッセージで「おなじURLの連続POSTだから再展開しないよ」と表示
- [ ] HOPE: URLにコメントのハッシュ #note-3 が付いてたら、チケット本文ではなくコメントの方を表示してほしい（これは連続POSTとみなさない）

**Comment by altnight** [comment]
## note を展開
`ticket.journals.values()` から更新履歴(notes)を取得して表示
動作的に問題なさそう
<img width="854" alt="g154-note-expand" src="https://user-images.githubusercontent.com/314365/44180844-8f0cf900-a139-11e8-9cae-ec4458240f11.png">

**Comment by shimizukawa** [comment]
![image](https://user-images.githubusercontent.com/151623/44181107-c0d28f80-a13a-11e8-85d4-e1b7977cc134.png)

**Comment by altnight** [comment]
TODO:

- リンクに `"note-x`をつけて表示みてみる
- 更新時にコメントの本文がないときは `(本文なし)` というような表示をする
  - チケット説明に fallback してもあまりうれしくはなさそう
  - スレッド返信しないと「バグかな?」と思われそう(挙動が変わる理由は外部からみえない)
  - `(本文なし)` みたいな説明しておいたほうが未開発発展途上感あって変更しやすそう

コードを整理したらPR予定。あといちおう仕様を簡単にまとめておきたい。

**Comment by altnight** [comment]
# 今回の対応

* Redmine URL が含まれている場合、通常の返信後に説明文をスレッドでリプライする
  * 説明文があるとき: チケットの説明文
  * コメントがあるとき: コメントの本文
  * 説明の本文がないとき: `(本文なし)`
  * コメントの本文がないとき: `(本文なし)`
* コメントあるかどうかの判定
  * `issues/xxxxx-#note-N` を正規表現で取得できるかどうか

**Comment by altnight** [comment]
- 残件: https://github.com/beproud/beproudbot/issues/158
  - `SHOULD: 8時間以内におなじURLをPOSTされたら、POSTした人にだけ見えるメッセージで「おなじURLの連続POSTだから再展開しないよ」と表示`

**Comment by shimizukawa** [comment]
やったぜ！
altnight++ botカイゼン
