### ISSUE TITLE
who plugin の実装

### ISSUE THREAD

**Issue by takanory** [beproud/beproudbot#16]
### 目的

- WhoとAlias情報を管理するコマンドを作成する
- もとのbotでは DjangoAdmin を使っていたが、コマンドでもよいのでは感

### スキーマ

```
(beproudbot@project-db) [beproudbot]> show columns from who_map;
+----------+--------------+------+-----+---------+----------------+
| Field    | Type         | Null | Key | Default | Extra          |
+----------+--------------+------+-----+---------+----------------+
| id       | int(11)      | NO   | PRI | NULL    | auto_increment |
| skype_id | varchar(100) | NO   |     | NULL    |                |
| name     | varchar(100) | NO   |     | NULL    |                |
| ctime    | datetime     | NO   |     | NULL    |                |
+----------+--------------+------+-----+---------+----------------+
4 rows in set (0.01 sec)
```
```
(beproudbot@project-db) [beproudbot]> show columns from whomap_name_alias;
+------------+--------------+------+-----+---------+----------------+
| Field      | Type         | Null | Key | Default | Extra          |
+------------+--------------+------+-----+---------+----------------+
| id         | int(11)      | NO   | PRI | NULL    | auto_increment |
| skype_id   | varchar(200) | NO   |     | NULL    |                |
| alias_name | varchar(200) | NO   |     | NULL    |                |
| ctime      | datetime     | NO   |     | NULL    |                |
+------------+--------------+------+-----+---------+----------------+
4 rows in set (0.00 sec)
```

### 入出力

- `$alias show [user_name]`: Slackのユーザーに紐づいているエイリアス名一覧を表示する
- `$alias add/del [user_name] <alias_name>`: Slackのユーザーに紐づくエイリアス名を更新する
- `$alias help`: aliasコマンドの使い方を返す

### 関連機能、影響範囲

- Who model は cleaning, kudo, thx で使用されている
- Alias model は thx で使用されているリグレッションの確認が必要となる箇所

### セキュリティ

- とくになし

**Comment by wanshot** [comment]
`who_map`,  `whomap_name_alias` テーブルから `skype_id` カラムを無くして、`whomap_name_alias` に `who_map` の外部キー持たせる方向で進めて問題ない？

**Comment by takanory** [comment]
skype_idは削除でいいと思う。 

who_map に slack の user id 、 username が入ったら、いちいちAPI叩かなくても slack の user id から username 生成できていいなとか思ったけど、まぁ気にすることもないか

**Comment by altnight** [comment]
takanory さんとかぶりますが、 skype_id は skype bot のときに内部IDと表示名が違ったから必要だったので、削除で問題ないです。slack_id として保持してもいいかもしれない

`$who del username` で消せるのは賛成なんですけど、普通に使っている　username を間違えて消してしまわないような仕組みがあったほうがいいかなぁと思いました。あるいは定期的にバックアップを取っておけばいいかな

**Comment by wanshot** [comment]
slack_idを削除するのはｒｙです。

> slack_id として保持
who_mapテーブルをslack_idカラムのみにして、whomap_name_aliasにnameカラムを用意するという風にした方がいいかもしれないですね。

> username を間違えて消してしまわないような仕組みがあったほうがいいかなぁ
- 特定のチャンネルからしか操作できないようにする(非公開コマンド)
- RedBullで使っているような再度入力させて誤入力防止

**Comment by wanshot** [comment]
実装したのでclose
https://github.com/beproud/beproudbot/pull/29
