### ISSUE TITLE
ドキュメントを記載するdocディレクトリの追加

### ISSUE THREAD

**Issue by wanshot** [beproud/beproudbot#27]
### 目的

- ドキュメントをmarkdownで記載するdocsディレクトリを作成する

### 入出力

- なし

### 関連機能、影響範囲

- なし

### セキュリティ

- なし

### デモ方法

- ドキュメントを追加した場合はgithubのWeb上から追加したブランチのdocs以下を表示して確認する

**Comment by takanory** [comment]
どういうドキュメントを置くつもりなのか、とりあえずファイルとタイトルだけでも置いておくとよいかと

**Comment by wanshot** [comment]
https://github.com/beproud/beproudbot/pull/28
