### ISSUE TITLE
Slackbot内で共通のバリデーター処理の追加

### ISSUE THREAD

**Issue by wanshot** [beproud/beproudbot#42]
# 目的

- 応答部分の可読性をあげるためバリデータを導入する
- 入力値の検証で同じような処理を複数のコマンドで使い分けるので、うまく切り出したい

## slackbot での基本的な応答の書き方

```
@respond_to('Give me (.*)')
def giveme(message, something):
    # ここで
    # - 入力値をチェックして(この例だと something変数)  
    # - 正常系と異常系のそれぞれの処理を書く
    # 必要がある
    message.reply('Here is {}'.format(something))
```

# 要求

- 予め与えられた選択肢の中に入力値が入っているかの検証ができる
- dbや外部APIなどへ存在チェックができる
- エラーになった場合 `message.send("エラーメッセージ")` できる

  - この動き自体はどのコマンドでも変わらなさそうなので、いちいちコマンドごとに書く必要がないようになっているよい

- (オプション) キャストができる

  - たとえば 日付が `YYYY-MM-DD` で与えられたら `date` オブジェクトにして返してくれる

# 入出力

- あとで書く

# 技術仕様

- https://github.com/lins05/slackbot/blob/develop/slackbot/manager.py#L71 を見る限り正規表現を名前付きにしても意味なさそう
- `argparse` を使うのも考えたが、入れるならコマンド単位以降でまるっと渡す書き方にした方がよさそう
   - 今後オプションを渡せるようなコマンドをつくるなら (例 `search=hoge --from 2016-10-11` のように条件つき検索みたいな)をやるなら `argparse` のほうがいいとおもう（これをreply_toの正規表現でマッチさせるのは無いので

# 関連機能、影響範囲

- あとで書く

# 参考

- https://github.com/lins05/slackbot#create-plugins
- https://github.com/pyconjp/pyconjpbot/blob/5ef03e5b06a4ff4fd589e152093d39c4c00f5aad/pyconjpbot/plugins/jira.py

**Comment by yyyk-bp** [comment]
本文更新した

argparseについて

- 入れるなら引数部分はまるっと渡す書き方にした方がよさそう

   ```
    import argparse

    @respond_to('cleaning add (.*)')
    def cleaning(message, arg_str):
        parser = argparse.ArgumentParser()
        args = parser.parse_args(arg_str.split(" ")) # 実際はエラーつかまえる必要がある
    ```

- 今後オプションを渡せるようなコマンドをつくるなら (例 `search=hoge --from 2016-10-11` のような条件つき検索みたいな)をやるなら `argparse` のほうがいいとおもう（これをreply_toの正規表現でマッチさせるのは無いので

**Comment by yyyk-bp** [comment]
argparse だとエラーの出し方はある程度制限されそう

**Comment by yyyk-bp** [comment]
@wanshot https://github.com/beproud/beproudbot/issues/42#issuecomment-280527504 argparse とりあえず無しでいいかなという感じがしてるんですが、どうでしょ

**Comment by wanshot** [comment]
@yyyk-bp 問題ないです、今上がっているコードをちらっと見た感じこれで十分だと思いました。

**Comment by yyyk-bp** [comment]
あざす。じゃあ多分このままPRなげます
