### ISSUE TITLE
pytest-flake8の挙動がおかしかったので普通のflake8にもどしてflake8-junit-reportをつかう

### ISSUE THREAD

**Issue by yyyk-bp** [beproud/beproudbot#51]
### 目的

- exclude効かない
- order-style google 効かない

  - https://github.com/tholo/pytest-flake8/blob/0.8.1/pytest_flake8.py#L48 対応してなさそう

- https://github.com/initios/flake8-junit-report は検討してみた結果うまくいきそう

### デモ方法

- 実行方法は `tox -e flake8` のまま

**Comment by shimizukawa** [comment]
あらまあ

**Comment by yyyk-bp** [comment]
https://github.com/beproud/beproudbot/pull/52#issuecomment-291367762 に書いたが事前flake8とxml出力はどっちをとるかという状況で、今回はテストそんなないのでxml出力をとる

**Comment by yyyk-bp** [comment]
https://github.com/beproud/beproudbot/pull/52 レビュー待ち化

**Comment by yyyk-bp** [comment]
#52 でマージしました
