### ISSUE TITLE
人をCleaningに追加する時に使いやすくなってほしい

### ISSUE THREAD

**Issue by jamesvandyne** [beproud/beproudbot#60]
### 目的

- $cleaning add james 木曜日
- $cleaning add james 木曜
- $cleaning add james 木
- $cleaning add james 木金
どれだっけ？？

cleaningに正しく追加する方法は覚えにくいです。入力は微妙に違っても処理をしたいです。

### 入出力

入力
- $cleaning add james 木曜日
- $cleaning add james 木曜
- $cleaning add james 木
- $cleaning add james 木金
- $cleaning add james 木テスト金

出力

- jamesさんが木曜日の掃除当番に追加されました
- jamesさんが木曜日の掃除当番に追加されました
- jamesさんが木曜日の掃除当番に追加されました
- jamesさんが木曜日と金曜日の掃除当番に追加されました
- jamesさんが木曜日と金曜日の掃除当番に追加されました

**Comment by NaoY-2501** [comment]
ほぼリモートに移行していて、掃除当番が形骸化している現状。いったんクローズします :bow:
