### ISSUE TITLE
$thx from hogeと$thx to hogeコマンドで添付するファイルをCSVファイルとする

### ISSUE THREAD

**Issue by wanshot** [beproud/beproudbot#74]
### 目的

- `$thx from hoge` と `$thx to hoge` は現状「file」というファイル名のバイナリがSlackに添付される、これでは不便なので「%Y%m%d-thx-(from|to)-user名.csv」というファイル名で添付されるように修正する

### 入出力

入力

- $thx from Slackユーザー名
- $thx to Slackユーザー名

出力

2018/01/01の場合: 20180101-thx-from-Slackユーザー名.csv

### 関連機能、影響範囲

- thxコマンド

### セキュリティ

- 特に無し

### デモ方法

- $thx from Slackユーザー名
- $thx to Slackユーザー名

**Comment by jamesvandyne** [comment]
#122 で対応したので、closeします
