### ISSUE TITLE
thx コマンドの word に空白文字を入れられない

### ISSUE THREAD

**Issue by yyyk-bp** [beproud/beproudbot#81]
### 目的

- thx の word に空白文字を入れられない現象が起きているので修正する

事例

```
こまった

[09:44] 
mtb_beta++ Dashboard もお返事ない


haroAPP [09:44] 
Dashboard(mtb_beta: 4GJ)

xiao [09:44] 
あれ
```

### 原因

- word のパターンが `(.*)\s*\+\+\s+(\S+)` になっている為

### 関連機能、影響範囲

- パターンの修正のみで対応できるはず

**Comment by wanshot** [comment]
#88 で対応したのでclose
