### ISSUE TITLE
ユーザーのAPIキーを登録する、チャンネルを登録する窓口を実装する

### ISSUE THREAD

**Issue by jamesvandyne** [beproud/beproudbot#86]
### 目的

- Redmineのユーザー認証を使うため、自分のAPIキーを登録できるようにする。
- プロジェクトとチャンネルを繋ぐコマンドを実装する

#### APIキー
- `/msg @haro $redmine key <api key>`      登録する
- `/msg @haro $redmine reset`       消す

#### 部屋とチャンネルを繋ぐ

部屋内で `$redmine add プロジェクト名`  を発言すると、登録する
部屋内で `$redmine remove` を 発言すると、消す

### 関連機能、影響範囲

ありません。

### セキュリティ

APIキーを登録するのは、DMでやります。

### デモ方法

なし

**Comment by wanshot** [comment]
https://github.com/beproud/beproudbot/pull/89
