### ISSUE TITLE
waterコマンドの改良

### ISSUE THREAD

**Issue by shimizukawa** [beproud/beproudbot#94]
### 目的

- `$water` を便利にする

### 入出力

1. `$water count` で一番知りたい情報を表示
    - 理由: 現在はcountが消費した日を表示している。追加した日を知るにはhistoryも必要
    - 入力: `$water count`
    - 出力: `残数: 4本 (11月21日 +9本, -0.57本/日)`
    - 補足: `$water` でも同じ機能を発動する。 `$water は予約語です` と言われても困るので。

2.  help の表示調整
    - 入力: `$water help`
    - 出力: `$water` と `$water count` が同じ機能だと分かるように書く

### 関連機能、影響範囲

- 互換性持たせてるので、影響範囲なしかな

### セキュリティ

- なし

### ケーススタディ

```
shimizukawa [09:31] 
$water

haroAPP [09:31] 
`$water`は予約語です

[09:32] 
$water help

haroAPP [09:32] 
- `$water count`: 現在の残数を返す
- `$water num`: 水を取り替えた時に使用。指定した数だけ残数を減らす(numが負数の場合、増やす)
- `$water history <num>`: 指定した件数分の履歴を返す(default=10)
- `$water help`: このコマンドの使い方を返す

shimizukawa [09:32] 
`$water num` は `$water <num>` のほうが良いな

[09:32] 
$water count

haroAPP [09:32] 
残数: 4本 (2017年11月28日 追加)

shimizukawa [09:33] 
追加というか、11/28(今日)減らしたのだ。
知りたいのは最後に追加（届いた）日付かな

[09:33] 
$water history

haroAPP [09:33] 
水の管理履歴:
[2017年11月28日]  3本 取替
[2017年11月28日]  1本 取替
[2017年11月24日]  1本 取替
[2017年11月21日]  9本 追加

shimizukawa
[09:36] 
`$water` だけ書いたら、次のように表示されると便利

残数: 4本 (11月21日 +9本, -0.57本/日)
```

**Comment by wanshot** [comment]
【提案】
`$water count で一番知りたい情報を表示`

人間が間違えて入力した場合、その履歴情報を修正する方法が今ないので  `$water history` 側に `$water count` の機能を寄せるというのはどうでしょう。

出力は以下を想定。
```
$water($water history)
残数: 4本 (11月21日 +9本, -0.57本/日)
水の管理履歴:
[2017年11月28日]  3本 取替
[2017年11月28日]  1本 取替
[2017年11月24日]  1本 取替
[2017年11月21日]  9本 追加
```

**Comment by shimizukawa** [comment]
んー、ちょっとエンジニア思考に寄ってるかな。
history見たいわけじゃないと思う

実際の行動からいま欲しい案はこんな感じ

消費したら予測
```
> $water 1

ウォーターサーバーのボトルを1本取りかえました。(残数: 4本)
12/5(火)に無くなります(11/21(火)+9本, -0.57本/日)
```

引数無しで現状を知りたい
```
> $water

残数: 4本
12/5(火)に無くなります(11/21(火)+9本, -0.57本/日)
12/5(火)に10本追加で12/22(金)に無くなります
```

んー、ここで履歴は知りたいだろうか？過去ログをみてhistory実行してるのがどんなときか分析するとよさそう

**Comment by NaoY-2501** [comment]
ほぼリモートに移行していて、オフィスで水を取り替える場面が減っているのでいったんクローズします。
ref.  https://beproud.slack.com/archives/C0106MV2C4F/p1604454146203500
```
xiao:cow2:  10:42
これとかもう要らなくなってそう
https://github.com/beproud/beproudbot/issues/94
```
