### ISSUE TITLE
バージョンもしくはリリースノートが帰ってくるコマンド

### ISSUE THREAD

**Issue by yyyk-bp** [beproud/beproudbot#95]
### 目的

- 更新が入った時に内容をわかりやすくする

### 入出力

入力例: 

`$haro version`

出力例: 

```
version 2017-11-11
# ChangeLog
- hoge
- huga

```

### 関連機能、影響範囲

- コマンドは単体で成り立つ。モデルに影響はしない
- バージョン情報をどっかで持つ必要があるかも
- ChangeLog は github へのリンクでもいいかもしれない

### セキュリティ

- TBD

**Comment by takanory** [comment]
* pyconjpbotでは単純にgitの中身を見て最新のバージョン情報を返してました

https://github.com/pyconjp/pyconjpbot/blob/master/pyconjpbot/plugins/misc.py#L54-L67

**Comment by NaoY-2501** [comment]
このissue担当します

**Comment by NaoY-2501** [comment]
requestsでChangeLog.rstを取得して、正規表現とかを使って最新部分だけを抽出する、というイメージ

**Comment by NaoY-2501** [comment]
https://github.com/beproud/beproudbot/issues/95 をmasterマージしたのでissueも閉じる。
