### ISSUE TITLE
lunch機能の復活

### ISSUE THREAD

**Issue by MatsLanGoH** [beproud/beproudbot#98]
### 目的

- 会社周辺のお店を紹介し、空腹状態での作業になってしまうことから守る。

### 入出力

- 入力する値、出力される結果を記載
- `$lunch` → `今日のランチはココ！＜お店情報＞会社から○○m`が1件返ってくる
- `$lunch <keyword>` →`今日のランチはここ！＜keyword条件にあうお店情報＞`が1件返ってくる。

### 関連機能、影響範囲

- なし

### セキュリティ

- なし

### デモ方法

- URLや、簡単に確認するための操作手順

### 参考

- [BPランチマップ](https://www.google.com/maps/d/viewer?mid=1J4U-QXOe1Zi_4Lw5UxaL8AriG6M&ll=35.68905030551246%2C139.58038133483888&z=13)

**Comment by wanshot** [comment]
https://github.com/beproud/beproudbot/pull/115
